version: '3.8'

services:
  api-test:
    container_name: sellia-api-test
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mongodb://mongo:27017/sellia
    depends_on:
      - mongo
    networks:
      - sellia-network

  client:
    container_name: sellia-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3001/api
    depends_on:
      - api-test
    networks:
      - sellia-network

  mongo:
    image: mongo:6
    container_name: sellia-mongo
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - sellia-network

volumes:
  mongo_data:

networks:
  sellia-network:
    driver: bridge
    name: sellia-network