# Digital Ocean App Platform Configuration
# This file can be used to deploy your app via the Digital Ocean CLI or UI

name: sellia-api
services:
- name: api
  source_dir: /api
  github:
    repo: DevelopFer/sellia-test
    branch: deploy/digital-ocean
  run_command: npm run start:prod
  build_command: npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /api
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "3000"
  - key: DATABASE_URL
    value: ${db.DATABASE_URL}
  - key: OPENAI_API_KEY
    value: ${OPENAI_API_KEY}
  - key: OPENAI_MODEL
    value: gpt-4o-mini
  - key: CORS_ORIGIN
    value: ${_self.URL}
  - key: JWT_SECRET
    value: ${JWT_SECRET}
  - key: RATE_LIMIT_MAX
    value: "100"
  - key: RATE_LIMIT_WINDOW_MS
    value: "900000"
  - key: LOG_LEVEL
    value: info

databases:
- name: sellia-mongodb
  engine: MONGODB
  version: "6"

# Optional: Add a managed database
# You can also use an external MongoDB service like MongoDB Atlas